'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.34209
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Controls
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Controls", GetType(Controls).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cat No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printCatNo() As String
            Get
                Return ResourceManager.GetString("printCatNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printClass() As String
            Get
                Return ResourceManager.GetString("printClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Customer PO No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printCustomerPoNo() As String
            Get
                Return ResourceManager.GetString("printCustomerPoNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Exciting Current ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printExcitingCurrent() As String
            Get
                Return ResourceManager.GetString("printExcitingCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Loss ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printLoss() As String
            Get
                Return ResourceManager.GetString("printLoss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Part Description ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printPartDescription() As String
            Get
                Return ResourceManager.GetString("printPartDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Serial No ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printSerialNo() As String
            Get
                Return ResourceManager.GetString("printSerialNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Cogent Power Inc. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property printTitle() As String
            Get
                Return ResourceManager.GetString("printTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Accepting Results with Error? ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sAcceptResultsWithError() As String
            Get
                Return ResourceManager.GetString("sAcceptResultsWithError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Amps ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sAmps() As String
            Get
                Return ResourceManager.GetString("sAmps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die AT-rms ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sATrms() As String
            Get
                Return ResourceManager.GetString("sATrms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die You are using harness ({0}), which is different from standard DgCore harness. Press CANCEL to change harness settings. Press OK to start the measurement. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessSettingsDgCore() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessSettingsDgCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Check harness ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessTitle() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Work order number of turns {0} does not match harness setting {1}. Press CANCEL to change harness settings. Press OK to start the measurement. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessWorkOrder() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessWorkOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Harness:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sHarness() As String
            Get
                Return ResourceManager.GetString("sHarness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Current result:  ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sResult() As String
            Get
                Return ResourceManager.GetString("sResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Error! Induction reached is out of range!
        '''Check harness cable and Shunt2 fuse! ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusFluxDensityOutOfRange() As String
            Get
                Return ResourceManager.GetString("sStatusFluxDensityOutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measurement finished ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementFinished() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measurement in progress ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementInProgress() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measurement interrupted ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementInterrupted() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementInterrupted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Measurement not started ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementNotStarted() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementNotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Your inserted weight is out of range. Please compare to nominal weight. ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusPleaseCheckWeight() As String
            Get
                Return ResourceManager.GetString("sStatusPleaseCheckWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Ready for operation ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sStatusReady() As String
            Get
                Return ResourceManager.GetString("sStatusReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Volts ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sVolts() As String
            Get
                Return ResourceManager.GetString("sVolts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Watts ähnelt.
        '''</summary>
        Friend Shared ReadOnly Property sWatts() As String
            Get
                Return ResourceManager.GetString("sWatts", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
