'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Controls
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Controls", GetType(Controls).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cat No.
        '''</summary>
        Friend Shared ReadOnly Property printCatNo() As String
            Get
                Return ResourceManager.GetString("printCatNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Class.
        '''</summary>
        Friend Shared ReadOnly Property printClass() As String
            Get
                Return ResourceManager.GetString("printClass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Customer PO No.
        '''</summary>
        Friend Shared ReadOnly Property printCustomerPoNo() As String
            Get
                Return ResourceManager.GetString("printCustomerPoNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exciting Current.
        '''</summary>
        Friend Shared ReadOnly Property printExcitingCurrent() As String
            Get
                Return ResourceManager.GetString("printExcitingCurrent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loss.
        '''</summary>
        Friend Shared ReadOnly Property printLoss() As String
            Get
                Return ResourceManager.GetString("printLoss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Part Description.
        '''</summary>
        Friend Shared ReadOnly Property printPartDescription() As String
            Get
                Return ResourceManager.GetString("printPartDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial No.
        '''</summary>
        Friend Shared ReadOnly Property printSerialNo() As String
            Get
                Return ResourceManager.GetString("printSerialNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cogent Power Inc..
        '''</summary>
        Friend Shared ReadOnly Property printTitle() As String
            Get
                Return ResourceManager.GetString("printTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Accepting Results with Error?.
        '''</summary>
        Friend Shared ReadOnly Property sAcceptResultsWithError() As String
            Get
                Return ResourceManager.GetString("sAcceptResultsWithError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amps.
        '''</summary>
        Friend Shared ReadOnly Property sAmps() As String
            Get
                Return ResourceManager.GetString("sAmps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AT-rms.
        '''</summary>
        Friend Shared ReadOnly Property sATrms() As String
            Get
                Return ResourceManager.GetString("sATrms", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are using harness ({0}), which is different from standard DgCore harness. Press CANCEL to change harness settings. Press OK to start the measurement..
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessSettingsDgCore() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessSettingsDgCore", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Check harness.
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessTitle() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Work order number of turns {0} does not match harness setting {1}. Press CANCEL to change harness settings. Press OK to start the measurement..
        '''</summary>
        Friend Shared ReadOnly Property sCheckHarnessWorkOrder() As String
            Get
                Return ResourceManager.GetString("sCheckHarnessWorkOrder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Harness: .
        '''</summary>
        Friend Shared ReadOnly Property sHarness() As String
            Get
                Return ResourceManager.GetString("sHarness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current result: .
        '''</summary>
        Friend Shared ReadOnly Property sResult() As String
            Get
                Return ResourceManager.GetString("sResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error! Induction reached is out of range!
        '''Check harness cable and Shunt2 fuse!.
        '''</summary>
        Friend Shared ReadOnly Property sStatusFluxDensityOutOfRange() As String
            Get
                Return ResourceManager.GetString("sStatusFluxDensityOutOfRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement finished.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementFinished() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementFinished", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement in progress.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementInProgress() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementInProgress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement interrupted.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementInterrupted() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementInterrupted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Measurement not started.
        '''</summary>
        Friend Shared ReadOnly Property sStatusMeasurementNotStarted() As String
            Get
                Return ResourceManager.GetString("sStatusMeasurementNotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your inserted weight is out of range. Please compare to nominal weight..
        '''</summary>
        Friend Shared ReadOnly Property sStatusPleaseCheckWeight() As String
            Get
                Return ResourceManager.GetString("sStatusPleaseCheckWeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ready for operation.
        '''</summary>
        Friend Shared ReadOnly Property sStatusReady() As String
            Get
                Return ResourceManager.GetString("sStatusReady", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volts.
        '''</summary>
        Friend Shared ReadOnly Property sVolts() As String
            Get
                Return ResourceManager.GetString("sVolts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Watts.
        '''</summary>
        Friend Shared ReadOnly Property sWatts() As String
            Get
                Return ResourceManager.GetString("sWatts", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
